checkoutLocation: "." #OR: replace with another folder name

image:
  file: .gitpod.Dockerfile

# Ports to expose on workspace startup
ports:
  - name: web-app
    description: Symfony Application running
    port: 8000
    onOpen: open-browser # OR: open-preview, notify, ignore
    visibility: private # OR: public

# Commands for execution
tasks:
  - name: Initialize workspace
    before: sh ./bash/initial-setup.sh
    init: echo "==> NO INIT SCRIPT"
    command: echo "==> NO COMMAND SCRIPT"
    openMode: split-right #OR: split-left, tab-after, tab-before